version: 2
updates:
- package-ecosystem: nuget
  directory: "/src/Stryker.CLI"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: System.IO.Abstractions.TestingHelpers
    versions:
    - 13.2.10
    - 13.2.11
    - 13.2.13
    - 13.2.14
    - 13.2.15
    - 13.2.16
    - 13.2.18
    - 13.2.20
    - 13.2.22
    - 13.2.23
    - 13.2.24
    - 13.2.25
    - 13.2.27
    - 13.2.28
  - dependency-name: System.IO.Abstractions
    versions:
    - 13.2.10
    - 13.2.11
    - 13.2.13
    - 13.2.14
    - 13.2.15
    - 13.2.16
    - 13.2.18
    - 13.2.20
    - 13.2.22
    - 13.2.23
    - 13.2.24
    - 13.2.25
    - 13.2.27
    - 13.2.28
  - dependency-name: NuGet.Versioning
    versions:
    - 5.9.0
- package-ecosystem: nuget
  directory: "/src/Stryker.Core/Stryker.Core/ToolHelpers"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: nuget
  directory: "/integrationtest"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: System.IO.Abstractions
    versions:
    - 13.2.10
    - 13.2.11
    - 13.2.13
    - 13.2.14
    - 13.2.15
    - 13.2.16
    - 13.2.17
    - 13.2.18
    - 13.2.20
    - 13.2.22
    - 13.2.23
    - 13.2.24
    - 13.2.25
    - 13.2.27
    - 13.2.28
  - dependency-name: Microsoft.TestPlatform.TranslationLayer
    versions:
    - 16.9.1
  - dependency-name: Microsoft.TestPlatform.Portable
    versions:
    - 16.9.1
  - dependency-name: Microsoft.TestPlatform.ObjectModel
    versions:
    - 16.9.1
  - dependency-name: Microsoft.TestPlatform
    versions:
    - 16.9.1
  - dependency-name: Microsoft.NET.Test.Sdk
    versions:
    - 16.9.1
  - dependency-name: nunit
    versions:
    - 3.13.1
- package-ecosystem: nuget
  directory: "/integrationtest/TargetProjects/NetFramework"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: MSTest.TestAdapter
    versions:
    - 2.1.2
    - 2.2.1
    - 2.2.2
  - dependency-name: MSTest.TestFramework
    versions:
    - 2.1.2
    - 2.2.1
    - 2.2.2
